version: '2'

services:

  counter:
    image: gcr.io/${PROJECT_ID}/gcb-docker-compose:latest
    container_name: counter
    depends_on:
      - redis
    ports:
      - "50051:50051"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

networks:
    default:
        external:
            name: cloudbuild
